<?php

namespace AppBundle\Repository;

/**
 * GeneratedNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneratedNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
